### ISSUE TITLE
broken test.js that stops the deployment of Github Pages of updates

### ISSUE THREAD

**Issue by niclaz** [web3privacy/data#2]
Just submitted a PR to edit an event within /data/src/events... then I noticed that there were tests failing in previous edits of codebase

See: https://github.com/web3privacy/data/actions/workflows/deploy.yml

It seems that the test broke 2 months ago: https://github.com/web3privacy/data/actions/runs/8459840597

[The previous commit](https://github.com/web3privacy/data/actions/runs/8459733846) did not change the code of the tests... 

Something broke in the deploy script...

**here are the errors thrown by the Github Deployer:** 

"Process completed with exit code 2.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: szenius/set-timezone@v1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

The following actions uses node12 which is deprecated and will be forced to run on node16: szenius/set-timezone@v1.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/"

Researching and attempting a fix in my own fork of repo

**Comment by niclaz** [comment]
Attempting to fix by changing deploy.yaml in /data/.github/workflows directory

'szenius/set-timezone@v1.0' was flagged by error thrown

**The package has been updated to v2.0: https://github.com/szenius/set-timezone**

### PR Created: https://github.com/web3privacy/data/pull/3

**Comment by burningtree** [comment]
Problem was invalid YAML files (or people definition):
- https://github.com/web3privacy/data/commit/fd02b734aa7546ed41e4f2d98e7eb9f37b524408
- https://github.com/web3privacy/data/commit/e275dfc9550bf0d06fa5e4bc90a476af8695fa00

Now it should be fixed and build work normally. Thanks for investigation!

**Comment by niclaz** [comment]
excellent, thanks for the links to the yamls. it lets me understand the file-structure a little bit better
